version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ AMQP port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  producer-service:
    image: khl40/ifolor.producer-service:latest
    container_name: producer-service
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    networks:
      - app-network

  consumer-service:
    image: khl40/ifolor.consumer-service:latest
    container_name: consumer-service
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    ports:
      - "9090:9090" # Metrics endpoint
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090" # Prometheus UI on 9091 to avoid conflict
    volumes:
      - ./prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - consumer-service
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000" # Grafana web UI
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge